import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="mx-auto mt-20 block border border-green-500 p-5  text-center text-red-500 underline">
        cleaned up!
      </h1>

      <div className="debug mx-auto inline-block p-5 text-center">
        <p className={styles.text_heading}>text heading</p>

        <p className={styles.text_heading_red}>text heading red</p>
      </div>
    </>
  );
}
