import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-red-500 block text-center border border-green-500 p-5  mx-auto mt-20 underline">
        cleaned up!
      </h1>
    </>
  );
}
